name: Auto Versioning (DISABLED)

on:
  # Deaktivováno pro první release - spouští se pouze manuálně
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to set (e.g. 0.0.1)'
        required: true
        default: '0.0.1'

jobs:
  version:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set Version
        id: version
        run: |
          echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          echo "Setting version to: ${{ github.event.inputs.version }}"
      
      - name: Update version.txt
        run: echo "${{ steps.version.outputs.VERSION }}" > version.txt
      
      - name: Commit version update
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add version.txt
          git commit -m "chore: update version to ${{ steps.version.outputs.VERSION }}" || exit 0
          git push
      
      - name: Create Tag
        run: git tag v${{ steps.version.outputs.VERSION }}
      
      - name: Push Tags
        run: git push origin --tags 